# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d6394b242faa31ed75aa470dd68b9d8250117244df1c38068b72a6b4fae49fc4cda485b81069c72c1231fbc6615526a73ea48e382034281787ddaf4bbcf59de

test:
  secret_key_base: 56b1fecf71022e3d6d00919f2e7821592153b40141517c0e1d920f8b245713eebedb03635b3d65f547b61f36f8f5708265173b5b9edd06f88b254e5841caf620

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
